title:             Blog.from('Juliana')
email:             juuh42dias@gmail.com
description:       ArtesÃ£ de software, transfeminista, pseudo escritora, aspirante a fotÃ³grafa, comedora de pamonha e movida a cafÃ© â˜•ğŸ’
author:            Juliana Dias Santos e Silva
baseurl:           "/blog"
url:               "https://juuh42dias.gitlab.io"

# Social Profiles
twitter_username:  juuh42dias
github_username:   juuh42dias
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - feedjira

# Content
contact: https://juuh42dias.gitlab.io

collections:
  - posts
